const { useEffect, useMemo, useState } = React;
const { createClient } = supabase;
const cfg = window.CSK_SUPABASE || {};
const configured = cfg.url && cfg.anonKey && !cfg.url.startsWith('COLOQUE_') && !cfg.anonKey.startsWith('COLOQUE_');
const client = configured ? createClient(cfg.url, cfg.anonKey) : null;
const EMPTY = { id:null, title:'', slug:'', category_id:'', excerpt:'', content:'', image_url:'', published:false };
const DEFAULT_CATS = ['Institucional','Direito','Mercado','Inovação'];

function slugify(v){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');}
function App(){
 const [session,setSession]=useState(null),[items,setItems]=useState([]),[cats,setCats]=useState([]),[form,setForm]=useState(EMPTY),[editing,setEditing]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('Todos'),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 useEffect(()=>{ if(!client){setLoading(false);return;} client.auth.getSession().then(({data})=>setSession(data.session)); const {data:sub}=client.auth.onAuthStateChange((_e,s)=>setSession(s)); return ()=>sub.subscription.unsubscribe(); },[]);
 useEffect(()=>{if(session) load();},[session]);
 async function load(){setLoading(true); const [{data:n,error:ne},{data:c,error:ce}]=await Promise.all([client.from('news').select('*').order('created_at',{ascending:false}),client.from('news_categories').select('*').order('name')]); if(ne||ce) flash((ne||ce).message); else {setItems(n||[]);setCats(c||[]);} setLoading(false);}
 function flash(t){setNotice(t);setTimeout(()=>setNotice(''),3200);}
 async function login(e){e.preventDefault();const {error}=await client.auth.signInWithPassword({email,password});if(error)flash(error.message);}
 async function logout(){await client.auth.signOut();setSession(null);}
 function change(k,v){setForm(f=>({...f,[k]:v}));}
 function reset(){setForm({...EMPTY,category_id:cats[0]?.id||''});setEditing(false);}
 async function save(e){e.preventDefault();if(!form.title.trim()||!form.content.trim())return flash('Título e conteúdo são obrigatórios.');let image=form.image_url;
  const file=document.querySelector('#news-image')?.files?.[0]; if(file){if(file.size>5*1024*1024)return flash('A imagem deve ter até 5 MB.');const ext=file.name.split('.').pop().toLowerCase();const path=`${crypto.randomUUID()}.${ext}`;const up=await client.storage.from('news-images').upload(path,file,{upsert:false});if(up.error)return flash(up.error.message);image=client.storage.from('news-images').getPublicUrl(path).data.publicUrl;}
  const payload={title:form.title.trim(),slug:slugify(form.title),category_id:form.category_id||null,excerpt:form.excerpt.trim(),content:form.content.trim(),image_url:image||null,published:!!form.published,published_at:form.published?(form.published_at||new Date().toISOString()):null};
  const result=editing?await client.from('news').update(payload).eq('id',form.id).select().single():await client.from('news').insert(payload).select().single(); if(result.error)return flash(result.error.message); flash(payload.published?'Notícia publicada.':'Rascunho salvo.');reset();load();}
 async function remove(id){if(!confirm('Excluir esta notícia?'))return;const {error}=await client.from('news').delete().eq('id',id);if(error)flash(error.message);else{flash('Notícia excluída.');load();}}
 async function toggle(item){const {error}=await client.from('news').update({published:!item.published,published_at:!item.published?new Date().toISOString():null}).eq('id',item.id);if(error)flash(error.message);else load();}
 async function addCategory(){const name=prompt('Nome da categoria:')?.trim();if(!name)return;const {data,error}=await client.from('news_categories').insert({name}).select().single();if(error)flash(error.message);else{setCats(v=>[...v,data].sort((a,b)=>a.name.localeCompare(b.name)));change('category_id',data.id);}}
 async function removeCategory(id){if(!confirm('Excluir esta categoria?'))return;const {error}=await client.from('news_categories').delete().eq('id',id);if(error)flash(error.message);else load();}
 const visible=useMemo(()=>items.filter(i=>(filter==='Todos'||i.category_id===filter)&&(`${i.title} ${i.excerpt||''}`).toLowerCase().includes(query.toLowerCase())),[items,filter,query]);
 if(!configured)return <div className="auth"><div className="auth-box"><b className="auth-logo">CSK</b><small>CONFIGURAÇÃO NECESSÁRIA</small><h1>Conecte o <i>Supabase.</i></h1><p>Edite <code>admin/config.js</code> e informe a URL e a chave <b>anon</b> do seu projeto. Não coloque a chave service_role no GitHub.</p><ol><li>Crie um projeto no Supabase.</li><li>Execute <code>admin/supabase.sql</code> no SQL Editor.</li><li>Preencha <code>admin/config.js</code>.</li></ol></div></div>;
 if(!session)return <div className="auth"><form className="auth-box" onSubmit={login}><b className="auth-logo">CSK</b><small>ÁREA RESTRITA</small><h1>Entrar no <i>painel.</i></h1><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{notice&&<div className="toast">{notice}</div>}<button className="primary">Entrar →</button></form></div>;
 return <div className="shell"><header className="topbar"><a className="brand" href="../index.html"><b>CSK</b><span>ADVOGADOS</span></a><div className="top-actions"><a href="../index.html">Ver site ↗</a><span>{session.user.email}</span><button onClick={logout}>Sair</button></div></header><main>
 <section className="heading"><div><small>ÁREA ADMINISTRATIVA</small><h1>Gestão de <i>notícias.</i></h1><p>Conteúdo persistente, protegido por autenticação e armazenado no Supabase.</p></div><div className="stats"><div><strong>{items.filter(i=>i.published).length}</strong><span>publicadas</span></div><div><strong>{items.filter(i=>!i.published).length}</strong><span>rascunhos</span></div><div><strong>{items.length}</strong><span>total</span></div></div></section>
 {notice&&<div className="toast">{notice}</div>}
 <section className="workspace"><form className="card editor" onSubmit={save}><div className="card-head"><div><small>{editing?'EDIÇÃO':'NOVA PUBLICAÇÃO'}</small><h2>{editing?'Editar notícia':'Nova notícia'}</h2></div><button type="button" className="ghost" onClick={reset}>Limpar</button></div><label>Título<input value={form.title} onChange={e=>change('title',e.target.value)} required placeholder="Título da notícia"/></label><div className="two"><label>Categoria<select value={form.category_id} onChange={e=>change('category_id',e.target.value)}><option value="">Sem categoria</option>{cats.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><button type="button" className="addcat" onClick={addCategory}>+ categoria</button></div><label>Resumo<textarea rows="3" value={form.excerpt||''} onChange={e=>change('excerpt',e.target.value)} placeholder="Resumo para o card da notícia"/></label><label>Conteúdo<textarea className="content" rows="11" value={form.content} onChange={e=>change('content',e.target.value)} required placeholder="Escreva o conteúdo da notícia."/></label><label>Foto principal<input id="news-image" type="file" accept="image/jpeg,image/png,image/webp"/></label>{form.image_url&&<div className="image-preview"><img src={form.image_url} alt="Prévia"/></div>}<label className="check"><input type="checkbox" checked={!!form.published} onChange={e=>change('published',e.target.checked)}/><span>Publicar imediatamente</span></label><button className="primary">{form.published?'Publicar notícia':'Salvar rascunho'} →</button></form>
 <aside><div className="card info"><small>CATEGORIAS</small><h3>Editorial CSK</h3><ul>{cats.map(c=><li key={c.id}>{c.name}<button onClick={()=>removeCategory(c.id)} title="Excluir">×</button></li>)}</ul><button className="text-button" onClick={addCategory}>+ Nova categoria</button></div><div className="card info"><small>ARMAZENAMENTO</small><h3>Supabase conectado</h3><p>Notícias e categorias ficam no banco. As imagens são armazenadas no bucket privado/público configurado no SQL.</p></div></aside></section>
 <section className="card publications"><div className="pub-head"><div><small>CONTEÚDO</small><h2>Publicações</h2></div><div className="tools"><input placeholder="Buscar..." value={query} onChange={e=>setQuery(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Todos</option>{cats.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div></div>{loading?<div className="empty">Carregando...</div>:visible.length===0?<div className="empty">Nenhuma notícia encontrada.</div>:visible.map(item=><article className="row" key={item.id}><div className="thumb">{item.image_url?<img src={item.image_url} alt=""/>:<span>CSK</span>}</div><div className="rowmain"><small>{cats.find(c=>c.id===item.category_id)?.name||'Sem categoria'} · {new Date(item.created_at).toLocaleDateString('pt-BR')}</small><h3>{item.title}</h3><p>{item.excerpt||'Sem resumo cadastrado.'}</p></div><span className={'status '+(item.published?'on':'')}>{item.published?'Publicada':'Rascunho'}</span><button onClick={()=>toggle(item)}>{item.published?'Despublicar':'Publicar'}</button><button onClick={()=>{setForm({...item});setEditing(true);scrollTo({top:0,behavior:'smooth'});}}>Editar</button><button className="danger" onClick={()=>remove(item.id)}>Excluir</button></article>)}</section>
 </main><footer>CSK | Cardoso Sena Kruschewsky Advogados <span>Painel de notícias · Supabase</span></footer></div>;
}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
